### ISSUE TITLE
BORIS v8.0.10 exponentially increasing lag if observation contains too many events

### ISSUE THREAD

**Issue by Lorhat** [olivierfriard/BORIS#430]
I recently downloaded the newest version of BORIS and am really enjoying the accuracy with which I can code now. This is a great addition.
However, I am running into a problem that seems to be amplified by higher video fps.
When coding videos with 60fps, BORIS starts lagging if there are more than 180-200 events in the event log of an observation. The response time seems to increase exponentially until it takes about 5sec for registering a pause command for example. This happens even if only 10-20 events are added from the point when BORIS starts lagging initially. Apart from the delay of registering commands, it is specifically the timestamp and frame counter that lag. 
Reducing the video playback speed to 0.900 reduces lag until a certain number of additional events (around 210-220 maybe). With 0.800 I can go even higher, etc.
Part of my videos are only 30fps. In their case, the lag doesn't start until just short of 300 events.
It seems like the refresh rate is too high, even for fast CPUs (mine running at 4.9GHz). (With BORIS v7, CPU load is very low, around 2%. Now (v8) it is around 15-16%).

Interestingly, downgrading to earlier versions such as v8.0.4 and v8.0.5 allows me to code around 100 events more until the lag starts, i.e., around 280 if the video has 60fps.

Since I am coding multiple trials of a study within one observation, I can copy and paste events of trials I am not coding at the moment into the observation description to temporarily reduce the number of events in the event log, as a workaround.

If the problem is indeed the refresh rate, and if possible, it would be very useful to be able to lower the refresh rate to hundreths of seconds instead of milliseconds, as an option in preferences.

I am using windows 10. Please let me know if you need further information. See also the txt file below.

Thank you and best regards
Luca

[Media File Information.txt](https://github.com/olivierfriard/BORIS/files/7038400/Media.File.Information.txt)

**Comment by olivierfriard** [comment]
Hi,
thank you for testing the new version.
I will try to reproduce this problem and let you know.
Thank you for your collaboration

**Comment by olivierfriard** [comment]
Did you refer to the v. 8.0.10 ?

**Comment by Lorhat** [comment]
Thank you for looking into this! Yes, I referred to version 8.0.10. However, the problem seems to exist in all experimental versions since v.8.0.4 (I did not try earlier versions). It seems most noticeable in v.8.0.10, i.e., in older versions I can code more events until the lag starts.

**Comment by olivierfriard** [comment]
The v. 8.0.11 should fix this issue. The hardware decoding was activated.
Please try it and let me know:
https://github.com/olivierfriard/BORIS/releases/tag/v8.0.11

**Comment by Lorhat** [comment]
Thank you for the update. At first, only the cmd window popped up, but closed a moment later, without launching BORIS. See the error log. It launched when I copied the mpv-1.dll from my v8.0.10 installation. Unfortunately, the lag still occurs, so coding becomes difficult starting from around 200 events in the event log (I used the same video based on which I uploaded the media file information.txt above, and another, equivalent one). 
Is the mpv-1.dll relevant to the update? If so, could you provide another experimental release with the most recent .dll included? If not, might there be a setting that I might need to check locally?
 
[boris_error.log](https://github.com/olivierfriard/BORIS/files/7109740/boris_error.log)

**Comment by olivierfriard** [comment]
Sorry for the mistake.
The v. 8.0.12 should fix this: https://github.com/olivierfriard/BORIS/releases/tag/v8.0.12
The mpv-1.dll was updated to the last version (2.0.0)

I tested it on Windows with a 1920x1080 60 FPS video and it is working without problem for up to 2000 events

The video decoding is done by basic first GPU (Intel HD Graphics 530). The NVIDIA GeForce GTX950M was not used.

![gpu_decoding](https://user-images.githubusercontent.com/6529122/132130346-fee69a50-369b-4c0f-9179-77c15722cb0e.png)

If you still have problem please send me a video sample and your project file. I will try to reproduce the problem.
See my email on the BORIS web site

**Comment by Lorhat** [comment]
The problem still persists, but the decoding is done by the dedicated RTX 3060. I will try v8.0.12 again using the internal gpu and let you know.
