### ISSUE TITLE
Incorrect "media file name" exported when event at time 00:00:000

### ISSUE THREAD

**Issue by Clarasauphar** [olivierfriard/BORIS#567]
Hi again :) Still working with my 16 videos at a time, I noticed when I export my results to excel, that the "media file name" is incorrect for every event measured at time 00:00:000 of one video. For the first event, I find in the column "media file name" : "not found". For the next observations, it will tell me the name of the file of the previous video but I know from the "time" column that it's supposed to be the next video file name.

**To Reproduce**
I am sorry, again I work with too much material to send it to you. But you might be able to reproduce the issue by loading several videos in an observation file and recording an event each time at 00:00:000, and a few in between to see what we are supposed to get once exported.
Then exporting the events in an excel file.

![image](https://user-images.githubusercontent.com/122974304/217210852-f9c8bc14-0c6d-4534-bb55-44cf6a993ff7.png)
![image](https://user-images.githubusercontent.com/122974304/217211278-76890408-2e6d-4c6b-a457-8bf490967e89.png)

 - OS: Windows 10
 - BORIS Version: v. 8.9.12 - 2023-01-18

Thank you for your help,

Clara

**Comment by Clarasauphar** [comment]
It look like it does not export those frames either at time 00:00:000

**Comment by olivierfriard** [comment]
Hi, thank you for reporting.

This issue should be fixed in v. 8.9.17 (release date: 2023-02-06)
Can you confirm this?

**Comment by Clarasauphar** [comment]
I am sorry the update did not fix the issue.

**Comment by olivierfriard** [comment]
Can you send me the output file via email? 
See the about page of BORIS web site

**Comment by Clarasauphar** [comment]
Sorry could you precise what you mean by output file ? Th excel or boris file ?

**Comment by olivierfriard** [comment]
The Excel or TSV file
Is it an aggregated events output?

If it is not a problem the BORIS project file should be useful also

**Comment by Clarasauphar** [comment]
no it is a tabular event not aggregated. I send you both by email.

**Comment by olivierfriard** [comment]
v. 8.9.18 should fix this issue.
See http://www.boris.unito.it/pages/download.html

Could you confirm this?

**Comment by Clarasauphar** [comment]
Yes it seems that it solved the file name issue thank you ! :) Still missing a few images when I extracted event frames though.

**Comment by olivierfriard** [comment]
Can you open another issue for the extracted event frames problem?
